### ISSUE TITLE
Latest return null

### ISSUE THREAD

**Issue by djerfy** [djerfy/bonjourmadame-api-server#6]
Output:
```json
{
  "description":"Return latest picture URL",
  "node":"bonjourmadame.xorhak.io",
  "title":"BonjourMadame, Wednesday 5 (latest)",
  "url":null
}
```

**Comment by IMBiXx** [comment]
same issue since 12/08/2020 but with 11 retries 😭
`{"description":"Return random picture URL","node":"bonjourmadame-646fd895cd-8f5d9","retry":11,"title":"BonjourMadame, Sunday 16 (random)","url":null}`

**Comment by djerfy** [comment]
Pattern match updated since 2020-08-16 (5c24fcf8004d70d6134caa5d466863396db00633)
